name: application
description: A starting point for Dart libraries or applications.
version: 1.0.0
publish_to: none

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  dependency:
    path: ../dependency/
  conduit_runtime:
    path: ../../runtime/
  meta: ^1.7.0
  reflectable: ^3.0.4

dev_dependencies:
  build_runner:
  build_test:
  lint: ^1.5.0
  test: ^1.16.5

dependency_overrides:
  conduit_isolate_exec:
    path: ../../isolate_exec
