name: conduit_config
version: 3.0.11
description: A safe and convenient way to read YAML configuration files.
repository: https://github.com/conduit-dart/conduit-config.git
environment:
  sdk: ">=2.12.0 <3.0.0"
dependencies:
  conduit_runtime: ^3.0.11
  meta: ^1.7.0
  reflectable: ^3.0.0
  yaml: ^3.1.0
dev_dependencies:
  build_runner:
  build_test:
  lint: ^1.5.0
  test: ^1.16.5
dependency_overrides:
  conduit_isolate_exec:
    path: ../isolate_exec
  conduit_runtime:
    path: ../runtime
